--
-- PostgreSQL database dump
--

--\restrict 9FvtUEGqjbMzba4SZBaWEmhLuNRjP5PCAIjCcT4RryrmW2fr4LyIEfiTCuRTQA9

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_items (
    quantity integer NOT NULL,
    cart_id bigint NOT NULL,
    id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.carts (
    active boolean NOT NULL,
    id bigint NOT NULL,
    user_id bigint
);


--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255)
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category_products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.category_products (
    category_id bigint NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: checkout_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.checkout_sessions (
    active boolean NOT NULL,
    cart_id bigint NOT NULL,
    user_id bigint NOT NULL,
    id uuid NOT NULL
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    total_amount numeric(38,2),
    cart_id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    current_transaction_id bigint,
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    user_id bigint NOT NULL,
    checkout_session_id uuid NOT NULL,
    payment_method character varying(255),
    shipping_address_string character varying(255),
    status character varying(255),
    CONSTRAINT orders_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CREDIT_CARD'::character varying, 'PAYPAL'::character varying, 'BANK_TRANSFER'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'PACKED'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_images (
    img_order integer,
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    image_uuid uuid NOT NULL
);


--
-- Name: product_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    price numeric(38,2),
    stock integer NOT NULL,
    id bigint NOT NULL,
    public_id uuid NOT NULL,
    thumbnail_uuid uuid,
    name character varying(100) NOT NULL,
    description character varying(500)
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipment_addresses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipment_addresses (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    public_id uuid NOT NULL,
    city character varying(255),
    country character varying(255),
    full_name character varying(255),
    phone_number character varying(255),
    street character varying(255),
    zip_code character varying(255)
);


--
-- Name: shipment_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipment_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipment_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shipment_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipment_items (
    quantity integer NOT NULL,
    product_id bigint NOT NULL,
    shipment_id bigint NOT NULL,
    id uuid NOT NULL,
    status character varying(255),
    CONSTRAINT shipment_items_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PACKING'::character varying, 'PACKED'::character varying])::text[])))
);


--
-- Name: shipments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipments (
    id bigint NOT NULL,
    order_order_id bigint NOT NULL,
    user_id bigint,
    address_string character varying(1000) NOT NULL,
    status character varying(255),
    tracking_number character varying(255),
    CONSTRAINT shipments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PACKING'::character varying, 'PACKED'::character varying, 'SHIPPED'::character varying, 'DELIVERED'::character varying])::text[])))
);


--
-- Name: shipments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    amount numeric(38,2),
    payment_method integer,
    created_at timestamp(6) with time zone,
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    transaction_id uuid NOT NULL,
    payment_token character varying(255),
    status character varying(255),
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    enabled boolean NOT NULL,
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255),
    role character varying(255),
    username character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_tokens (
    id bigint NOT NULL,
    user_id bigint,
    token uuid
);


--
-- Name: verification_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verification_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: category_products category_products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_products
    ADD CONSTRAINT category_products_pkey PRIMARY KEY (category_id, product_id);


--
-- Name: checkout_sessions checkout_sessions_cart_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT checkout_sessions_cart_id_key UNIQUE (cart_id);


--
-- Name: checkout_sessions checkout_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT checkout_sessions_pkey PRIMARY KEY (id);


--
-- Name: cart_items idx_cart_items_cart_id_product_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT idx_cart_items_cart_id_product_id UNIQUE (cart_id, product_id);


--
-- Name: orders orders_cart_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_cart_id_key UNIQUE (cart_id);


--
-- Name: orders orders_current_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_current_transaction_id_key UNIQUE (current_transaction_id);


--
-- Name: orders orders_order_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_order_id_key UNIQUE (order_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: product_images product_images_image_uuid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_image_uuid_key UNIQUE (image_uuid);


--
-- Name: product_images product_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: products products_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_public_id_key UNIQUE (public_id);


--
-- Name: shipment_addresses shipment_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_addresses
    ADD CONSTRAINT shipment_addresses_pkey PRIMARY KEY (id);


--
-- Name: shipment_addresses shipment_addresses_public_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_addresses
    ADD CONSTRAINT shipment_addresses_public_id_key UNIQUE (public_id);


--
-- Name: shipment_items shipment_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_items
    ADD CONSTRAINT shipment_items_pkey PRIMARY KEY (id);


--
-- Name: shipments shipments_order_order_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT shipments_order_order_id_key UNIQUE (order_order_id);


--
-- Name: shipments shipments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT shipments_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_transaction_id_key UNIQUE (transaction_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: verification_tokens verification_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_tokens
    ADD CONSTRAINT verification_tokens_pkey PRIMARY KEY (id);


--
-- Name: idx_order_checkout_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_checkout_session_id ON public.orders USING btree (checkout_session_id);


--
-- Name: idx_order_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_created_at ON public.orders USING btree (created_at);


--
-- Name: idx_order_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_order_id ON public.orders USING btree (order_id);


--
-- Name: idx_order_status_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_status_created_at ON public.orders USING btree (status, created_at);


--
-- Name: idx_order_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_order_user_id ON public.orders USING btree (user_id);


--
-- Name: idx_shipment_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_shipment_status ON public.shipments USING btree (status);


--
-- Name: idx_transaction_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_order_id ON public.transactions USING btree (order_id);


--
-- Name: idx_transaction_transaction_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaction_transaction_id ON public.transactions USING btree (transaction_id);


--
-- Name: idx_user_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_email ON public.users USING btree (email);


--
-- Name: idx_user_enabled; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_enabled ON public.users USING btree (enabled);


--
-- Name: idx_user_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_role ON public.users USING btree (role);


--
-- Name: idx_user_username; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_username ON public.users USING btree (username);


--
-- Name: cart_items fk1re40cjegsfvw58xrkdp6bac6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fk1re40cjegsfvw58xrkdp6bac6 FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: shipment_items fk4rh14gyym63tnsi2i95f61d7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_items
    ADD CONSTRAINT fk4rh14gyym63tnsi2i95f61d7 FOREIGN KEY (shipment_id) REFERENCES public.shipments(id);


--
-- Name: category_products fk58ip0foccc3ry5ohrot1vr3of; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_products
    ADD CONSTRAINT fk58ip0foccc3ry5ohrot1vr3of FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: orders fk594fgx8wpklcf3t41jq3grhlh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk594fgx8wpklcf3t41jq3grhlh FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: shipment_addresses fk68ta430s90xrhqsj49ry5t9e4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_addresses
    ADD CONSTRAINT fk68ta430s90xrhqsj49ry5t9e4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: shipment_items fk9u65rmaw3kmuujg4l90hxbpdq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_items
    ADD CONSTRAINT fk9u65rmaw3kmuujg4l90hxbpdq FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: shipments fkacls0n0aowv3qw29f7gajfwk6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT fkacls0n0aowv3qw29f7gajfwk6 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: orders fke5ptlbghos072wfscv3y5awo2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fke5ptlbghos072wfscv3y5awo2 FOREIGN KEY (current_transaction_id) REFERENCES public.transactions(id);


--
-- Name: transactions fkfyxndk58yiq2vpn0yd4m09kbt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkfyxndk58yiq2vpn0yd4m09kbt FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: checkout_sessions fkgr5xfsu4cw9oi3vvu3yrueq3w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT fkgr5xfsu4cw9oi3vvu3yrueq3w FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: checkout_sessions fkiou7qq53ymucnn9x50mg3u9eq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checkout_sessions
    ADD CONSTRAINT fkiou7qq53ymucnn9x50mg3u9eq FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: shipments fkk9e11cm2o0m1jgiapqpt6rm0j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipments
    ADD CONSTRAINT fkk9e11cm2o0m1jgiapqpt6rm0j FOREIGN KEY (order_order_id) REFERENCES public.orders(order_id);


--
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: category_products fkpr3kfk7ij874uqy9u846oc42o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.category_products
    ADD CONSTRAINT fkpr3kfk7ij874uqy9u846oc42o FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: product_images fkqnq71xsohugpqwf3c9gxmsuy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_images
    ADD CONSTRAINT fkqnq71xsohugpqwf3c9gxmsuy FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- PostgreSQL database dump complete
--

--\unrestrict 9FvtUEGqjbMzba4SZBaWEmhLuNRjP5PCAIjCcT4RryrmW2fr4LyIEfiTCuRTQA9

