-- src/main/resources/db/migration/V3__add_prt.sql

-- Migration V3: Add Password Recovery Tokens Table

CREATE TABLE pass_recovery_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
        TIME ZONE,
        expires_at TIMESTAMP(6)
    WITH
        TIME ZONE,
        token VARCHAR(100) NOT NULL,
        user_id BIGINT NOT NULL,
        PRIMARY KEY (id)
);

CREATE INDEX idx_token ON pass_recovery_tokens (token);

CREATE INDEX idx_expires_at ON pass_recovery_tokens (expires_at);

CREATE INDEX idx_user_id ON pass_recovery_tokens (user_id);

ALTER TABLE IF EXISTS pass_recovery_tokens
DROP CONSTRAINT IF EXISTS UKibc8l0tediekocjjd21hgoy9o;

ALTER TABLE IF EXISTS pass_recovery_tokens
ADD CONSTRAINT UKibc8l0tediekocjjd21hgoy9o UNIQUE (token);

ALTER TABLE IF EXISTS pass_recovery_tokens
ADD CONSTRAINT FK4djuixwedeku4lo0n0co7akww FOREIGN KEY (user_id) REFERENCES users;

-- End of Migration V3