-- src/main/resources/db/migration/V5__add_reviews_table.sql

-- Migration V5: Add Reviews Table and indexes cleanup


DROP INDEX IF EXISTS idx_token;

DROP INDEX IF EXISTS idx_expires_at;

DROP INDEX IF EXISTS idx_user_id;

CREATE INDEX idx_prt_token ON pass_recovery_tokens (token);

CREATE INDEX idx_prt_expires_at ON pass_recovery_tokens (expires_at);

CREATE INDEX idx_prt_user_id ON pass_recovery_tokens (user_id);

CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6)
    WITH
        TIME ZONE,
    rating INT NOT NULL,
    comment VARCHAR(1000),
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS reviews
ADD CONSTRAINT FK_reviews_user FOREIGN KEY (user_id) REFERENCES users ON DELETE CASCADE;

ALTER TABLE IF EXISTS reviews
ADD CONSTRAINT FK_reviews_product FOREIGN KEY (product_id) REFERENCES products ON DELETE CASCADE;

CREATE INDEX idx_reviews_user_id ON reviews (user_id);

CREATE INDEX idx_reviews_product_id ON reviews (product_id);

-- End of Migration V5

